#!/bin/bash

echo "🧪 ローカルパッケージのテスト手順"
echo "================================"
echo ""
echo "1️⃣  現在のディレクトリでパッケージをリンク:"
echo "   npm link"
echo ""
echo "2️⃣  別のテスト用ディレクトリを作成:"
echo "   mkdir ~/test-agile-package"
echo "   cd ~/test-agile-package"
echo "   npm init -y"
echo ""
echo "3️⃣  パッケージをリンクしてインストール:"
echo "   npm link @pandalize/agile-github-suite"
echo ""
echo "4️⃣  テストファイルを作成して動作確認:"
echo "   cat > test.js << 'EOF'"
echo "   const agile = require('@pandalize/agile-github-suite');"
echo "   console.log('Package loaded:', agile);"
echo "   console.log('Version:', agile.version);"
echo "   console.log('Message:', agile.message);"
echo "   EOF"
echo ""
echo "   node test.js"
echo ""
echo "5️⃣  テスト後のクリーンアップ:"
echo "   npm unlink @pandalize/agile-github-suite"
echo "   cd ~/workspace/agile"
echo "   npm unlink"
echo ""